### PR TITLE
Addition of the Boursorama BrokerAdapter

### PR DESCRIPTION
**Pull request by vivienbo**
There are more than 160,000 French citizens living in Belgium. Only two French banks accept to open accounts (including Trading Accounts) for French citizens which are not French fiscal resident: Fortuneo and Boursorama Banque.

Therefore, Boursorama is likely to be a common choice for Belgian-resident French citizens who are looking for low cost investment:
* most XPAR and XAMS iShare ETF's are 0€ fee even if you buy 20 times a month;
* 0.60% fee with 1.99€/transaction minimum on most other securities
* Backed by a Physical Bank (100% subsidiary of Société Générale)
* Main drawback is they have a minimum 100€ value threshold to introduce an operation

Includes:
- [x] 3 Unit tests from 3 different months (including if user exports cash transactions)
- [x] Optimized code based on Boursorama CSV
- [x] Documentation on how to export the Boursorama CSV

Notes:
* I could not test transactions in USD. Boursorama does not have a currency column and the associated bank account is labelled in EUR so my assumption is they only provide extracts in EUR. Open an issue with sample dataset in case that's not the case.

### CODE REVIEW

**Comment by vivienbo** [comment]
Reason this PR does not build is linked to
```
PS F:\Repositories\contribution\tobcalc> deno bundle web_export.ts site/public/tobcalc-lib.js            
(...)
error: Module not found "file:///F:/Repositories/contribution/tobcalc/src/registered_funds.ts".
    at file:///F:/Repositories/contribution/tobcalc/src/tax.ts:8:42
```
This is because registered_fund.ts is not available in the `master` branch of [samjmck/tobcalc](https://github.com/samjmck/tobcalc)

**Comment by samjmck** [comment]
> Reason this PR does not build seems to be linked to
> 
> ```
> PS F:\Repositories\contribution\tobcalc> deno bundle web_export.ts site/public/tobcalc-lib.js            
> (...)
> error: Module not found "file:///F:/Repositories/contribution/tobcalc/src/registered_funds.ts".
>     at file:///F:/Repositories/contribution/tobcalc/src/tax.ts:8:42
> ```
> 
> This is because `registered_fund.ts` is not available in the `master` branch of [samjmck/tobcalc](https://github.com/samjmck/tobcalc)
> 
> I think only @samjmck can resolve this prior to PR merge. Happy to help if I can.

Added some docs on why this is the case in [13a7800](https://github.com/samjmck/tobcalc/commit/13a7800e8b7f12bfa7a9b4965c39381dc7c80278)

**Comment by samjmck** [comment]
Looks good, thanks for your hard work! This will definitely be appreciated by Boursorama users, I wasn't aware this was so popular with French citizens.

**Comment by samjmck** [comment]
I'm working on some changes to the way that we parse transactions so that we could potentially reuse the broker parsers for other things, such as the new capital gains tax in Belgium. I wanted to ask, in the following Boursorama csv:

```
"Date opération";"Date valeur";Opération;Valeur;"Code ISIN";Montant;Quantité
06/02/2023;08/02/2023;"ACHAT COMPTANT ETR";"ISHS COR MSCI WLD";IE00B4L5Y983;-219.24;3.0
02/02/2023;06/02/2023;"ACHAT COMPTANT ETR";"ISHS COR MSCI WLD";IE00B4L5Y983;-144.66;2.0
```

Are these sell or buy transactions? I'm assuming buy?

**Comment by samjmck** [comment]
Do you have some sell transactions by any chance?

**Pull request merged**
